import { Games, HomeIcon ,LiveIcon,PopularIcon, StopWatch, VirtualIcons } from './components/right-navigation-components/icons';

export const mainGroupingsArray = [
    {
        name: 'TOURNAMENTS',
        countries: null,
        leagues:["soccer_epl","soccer_uefa_champs_league_qualification","soccer_uefa_euro_qualification","soccer_uefa_europa_league","soccer_uefa_europa_conference_league","soccer_italy_serie_a","soccer_germany_bundesliga","soccer_spain_la_liga","soccer_england_league1"]
    },
    { name:'POPULAR COUNTRIES',countries:["England","France","Germany","Italy","Spain"],leagues:null}
    ,{name:'OTHER COUNTRIES',countries:null,leagues:null}
]



export const rightNavMainItems = [
    { name: "HOME" ,icon :HomeIcon},
    { name: "LIVE NOW ",icon:LiveIcon },
    {name: "UPCOMING",icon:StopWatch}
    ,{name:"GAMES",icon:Games}
    , { name:"POPULAR",icon:PopularIcon}
]

export const leagueToCountry = {
    "americanfootball_cfl": "Canada",
    "americanfootball_ncaaf": "United States",
    "americanfootball_nfl": "United States",
    "americanfootball_nfl_preseason": "United States",
    "americanfootball_ufl": "United States",
    "aussierules_afl": "Australia",
    "baseball_mlb": "United States",
    "baseball_mlb_preseason": "United States",
    "baseball_ncaa": "United States",
    "basketball_euroleague": "Europe",
    "basketball_nba": "United States",
    "basketball_nba_preseason": "United States",
    "basketball_ncaab": "United States",
    "basketball_wnba": "United States",
    "boxing_boxing": "Global",
    "cricket_asia_cup": "Asia",
    "cricket_big_bash": "Australia",
    "cricket_caribbean_premier_league": "Caribbean",
    "cricket_icc_world_cup": "Global",
    "cricket_international_t20": "Global",
    "cricket_ipl": "India",
    "cricket_odi": "Global",
    "cricket_psl": "Pakistan",
    "cricket_t20_blast": "England",
    "cricket_test_match": "Global",
    "cricket_the_hundred": "England",
    "icehockey_nhl": "United States",
    "icehockey_sweden_allsvenskan": "Sweden",
    "icehockey_sweden_hockey_league": "Sweden",
    "mma_mixed_martial_arts": "Global",
    "rugbyleague_nrl": "Australia",
    "rugbyunion_world_cup": "Global",
    "soccer_africa_cup_of_nations": "Africa",
    "soccer_argentina_primera_division": "Argentina",
    "soccer_australia_aleague": "Australia",
    "soccer_austria_bundesliga": "Austria",
    "soccer_belgium_first_div": "Belgium",
    "soccer_brazil_campeonato": "Brazil",
    "soccer_brazil_serie_b": "Brazil",
    "soccer_chile_campeonato": "Chile",
    "soccer_china_superleague": "China",
    "soccer_conmebol_copa_libertadores": "South America",
    "soccer_denmark_superliga": "Denmark",
    "soccer_efl_champ": "England",
    "soccer_england_efl_cup": "England",
    "soccer_england_league1": "England",
    "soccer_england_league2": "England",
    "soccer_epl": "England",
    "soccer_fa_cup": "England",
    "soccer_fifa_world_cup": "Global",
    "soccer_fifa_world_cup_womens": "Global",
    "soccer_finland_veikkausliiga": "Finland",
    "soccer_france_ligue_one": "France",
    "soccer_france_ligue_two": "France",
    "soccer_germany_bundesliga": "Germany",
    "soccer_germany_bundesliga2": "Germany",
    "soccer_germany_liga3": "Germany",
    "soccer_greece_super_league": "Greece",
    "soccer_italy_serie_a": "Italy",
    "soccer_italy_serie_b": "Italy",
    "soccer_japan_j_league": "Japan",
    "soccer_korea_kleague1": "South Korea",
    "soccer_league_of_ireland": "Ireland",
    "soccer_mexico_ligamx": "Mexico",
    "soccer_netherlands_eredivisie": "Netherlands",
    "soccer_norway_eliteserien": "Norway",
    "soccer_poland_ekstraklasa": "Poland",
    "soccer_portugal_primeira_liga": "Portugal",
    "soccer_spain_la_liga": "Spain",
    "soccer_spain_segunda_division": "Spain",
    "soccer_spl": "Scotland",
    "soccer_sweden_allsvenskan": "Sweden",
    "soccer_sweden_superettan": "Sweden",
    "soccer_switzerland_superleague": "Switzerland",
    "soccer_turkey_super_league": "Turkey",
    "soccer_uefa_champs_league": "Europe",
    "soccer_uefa_champs_league_qualification": "Europe",
    "soccer_uefa_euro_qualification": "Europe",
    "soccer_uefa_europa_conference_league": "Europe",
    "soccer_uefa_europa_league": "Europe",
    "soccer_uefa_nations_league": "Europe",
    "soccer_usa_mls": "United States",
    "tennis_atp_aus_open_singles": "Australia",
    "tennis_atp_french_open": "France",
    "tennis_atp_us_open": "United States",
    "tennis_atp_wimbledon": "United Kingdom",
    "tennis_wta_aus_open_singles": "Australia",
    "tennis_wta_french_open": "France",
    "tennis_wta_us_open": "United States",
    "tennis_wta_wimbledon": "United Kingdom"
  }
  
